include: parking_no_base.yaml
task: "parking_step-by-step"

generation_kwargs:
  max_new_tokens: 8192
  do_sample: false
  temperature: 0.0
  parking_step_by_step: true

lmms_eval_specific_kwargs:
  default:
    parking_prompt_mode: step_by_step
    parking_image_root: ./data/parking
