include: onet.yaml
task: "onet_aux_step-by-step"

generation_kwargs:
  max_new_tokens: 8192
  do_sample: false
  temperature: 0.0
  onet_step_by_step: true

lmms_eval_specific_kwargs:
  default:
    onet_prompt_mode: aux_step_by_step
    onet_image_root: ./data/onet
